/* 
 * Closelink API
 *
 * This is the documentation of the public Closelink API. For now it contains all routes to manage Stocks and Schedules for specific vessels.
 *
 * OpenAPI spec version: v1
 * Contact: service@closelink.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


namespace CloselinkAPI.Client
{
    /// <summary>
    /// Represents a readable-only configuration contract.
    /// </summary>
    public interface IReadableConfiguration
    {

        /// <summary>
        /// Gets the API key.
        /// </summary>
        /// <value>API key.</value>
        string ApiKey { get; }

        /// <summary>
        /// Gets the base path.
        /// </summary>
        /// <value>Base path.</value>
        string BasePath { get; }


        /// <summary>
        /// Gets the HTTP connection timeout (in milliseconds)
        /// </summary>
        /// <value>HTTP connection timeout.</value>
        int Timeout { get; }

        /// <summary>
        /// Gets the user agent.
        /// </summary>
        /// <value>User agent.</value>
        string UserAgent { get; }
    }
}
