/* 
 * Closelink API
 *
 * This is the documentation of the public Closelink API. For now it contains all routes to manage Stocks and Schedules for specific vessels.
 *
 * OpenAPI spec version: v1
 * Contact: service@closelink.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = CloselinkAPI.Client.SwaggerDateConverter;

namespace CloselinkAPI.Model
{
    /// <summary>
    /// Schedule Entry for a vessel
    /// </summary>
    [DataContract]
    public partial class Schedule :  IEquatable<Schedule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Schedule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Schedule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Schedule" /> class.
        /// </summary>
        /// <param name="id">Internal id (read-only).</param>
        /// <param name="dateCreated">The date-time the object was created (read-only).</param>
        /// <param name="dateUpdated">The date-time the object was last updated (read-only).</param>
        /// <param name="customerId">Internal customerId (read-only).</param>
        /// <param name="imo">The imo of the vessel (required).</param>
        /// <param name="eta">The estimated time of arrival (required).</param>
        /// <param name="etd">The estimated time of departure (required).</param>
        /// <param name="locode">The locode of the port (required).</param>
        public Schedule(string id = default(string), DateTime? dateCreated = default(DateTime?), DateTime? dateUpdated = default(DateTime?), string customerId = default(string), string imo = default(string), DateTime? eta = default(DateTime?), DateTime? etd = default(DateTime?), string locode = default(string))
        {
            // to ensure "imo" is required (not null)
            if (imo == null)
            {
                throw new InvalidDataException("imo is a required property for Schedule and cannot be null");
            }
            else
            {
                this.Imo = imo;
            }
            // to ensure "eta" is required (not null)
            if (eta == null)
            {
                throw new InvalidDataException("eta is a required property for Schedule and cannot be null");
            }
            else
            {
                this.Eta = eta;
            }
            // to ensure "etd" is required (not null)
            if (etd == null)
            {
                throw new InvalidDataException("etd is a required property for Schedule and cannot be null");
            }
            else
            {
                this.Etd = etd;
            }
            // to ensure "locode" is required (not null)
            if (locode == null)
            {
                throw new InvalidDataException("locode is a required property for Schedule and cannot be null");
            }
            else
            {
                this.Locode = locode;
            }
            this.Id = id;
            this.DateCreated = dateCreated;
            this.DateUpdated = dateUpdated;
            this.CustomerId = customerId;
        }
        
        /// <summary>
        /// Internal id (read-only)
        /// </summary>
        /// <value>Internal id (read-only)</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The date-time the object was created (read-only)
        /// </summary>
        /// <value>The date-time the object was created (read-only)</value>
        [DataMember(Name="dateCreated", EmitDefaultValue=false)]
        public DateTime? DateCreated { get; set; }

        /// <summary>
        /// The date-time the object was last updated (read-only)
        /// </summary>
        /// <value>The date-time the object was last updated (read-only)</value>
        [DataMember(Name="dateUpdated", EmitDefaultValue=false)]
        public DateTime? DateUpdated { get; set; }

        /// <summary>
        /// Internal customerId (read-only)
        /// </summary>
        /// <value>Internal customerId (read-only)</value>
        [DataMember(Name="customerId", EmitDefaultValue=false)]
        public string CustomerId { get; set; }

        /// <summary>
        /// The imo of the vessel
        /// </summary>
        /// <value>The imo of the vessel</value>
        [DataMember(Name="imo", EmitDefaultValue=false)]
        public string Imo { get; set; }

        /// <summary>
        /// The estimated time of arrival
        /// </summary>
        /// <value>The estimated time of arrival</value>
        [DataMember(Name="eta", EmitDefaultValue=false)]
        public DateTime? Eta { get; set; }

        /// <summary>
        /// The estimated time of departure
        /// </summary>
        /// <value>The estimated time of departure</value>
        [DataMember(Name="etd", EmitDefaultValue=false)]
        public DateTime? Etd { get; set; }

        /// <summary>
        /// The locode of the port
        /// </summary>
        /// <value>The locode of the port</value>
        [DataMember(Name="locode", EmitDefaultValue=false)]
        public string Locode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Schedule {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DateCreated: ").Append(DateCreated).Append("\n");
            sb.Append("  DateUpdated: ").Append(DateUpdated).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Imo: ").Append(Imo).Append("\n");
            sb.Append("  Eta: ").Append(Eta).Append("\n");
            sb.Append("  Etd: ").Append(Etd).Append("\n");
            sb.Append("  Locode: ").Append(Locode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Schedule);
        }

        /// <summary>
        /// Returns true if Schedule instances are equal
        /// </summary>
        /// <param name="input">Instance of Schedule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Schedule input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DateCreated == input.DateCreated ||
                    (this.DateCreated != null &&
                    this.DateCreated.Equals(input.DateCreated))
                ) && 
                (
                    this.DateUpdated == input.DateUpdated ||
                    (this.DateUpdated != null &&
                    this.DateUpdated.Equals(input.DateUpdated))
                ) && 
                (
                    this.CustomerId == input.CustomerId ||
                    (this.CustomerId != null &&
                    this.CustomerId.Equals(input.CustomerId))
                ) && 
                (
                    this.Imo == input.Imo ||
                    (this.Imo != null &&
                    this.Imo.Equals(input.Imo))
                ) && 
                (
                    this.Eta == input.Eta ||
                    (this.Eta != null &&
                    this.Eta.Equals(input.Eta))
                ) && 
                (
                    this.Etd == input.Etd ||
                    (this.Etd != null &&
                    this.Etd.Equals(input.Etd))
                ) && 
                (
                    this.Locode == input.Locode ||
                    (this.Locode != null &&
                    this.Locode.Equals(input.Locode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.DateCreated != null)
                    hashCode = hashCode * 59 + this.DateCreated.GetHashCode();
                if (this.DateUpdated != null)
                    hashCode = hashCode * 59 + this.DateUpdated.GetHashCode();
                if (this.CustomerId != null)
                    hashCode = hashCode * 59 + this.CustomerId.GetHashCode();
                if (this.Imo != null)
                    hashCode = hashCode * 59 + this.Imo.GetHashCode();
                if (this.Eta != null)
                    hashCode = hashCode * 59 + this.Eta.GetHashCode();
                if (this.Etd != null)
                    hashCode = hashCode * 59 + this.Etd.GetHashCode();
                if (this.Locode != null)
                    hashCode = hashCode * 59 + this.Locode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
