/* 
 * Closelink API
 *
 * This is the documentation of the public Closelink API. For now it contains all routes to manage Stocks and Schedules for specific vessels.
 *
 * OpenAPI spec version: v1
 * Contact: service@closelink.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using CloselinkAPI.Client;
using CloselinkAPI.Api;
using CloselinkAPI.Model;

namespace CloselinkAPI.Test
{
    /// <summary>
    ///  Class for testing StockApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class StockApiTests
    {
        private StockApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StockApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StockApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.Fail();
            Assert.IsInstanceOf(typeof(StockApi), instance, "instance is a StockApi");
        }

        
        /// <summary>
        /// Test PostStocks
        /// </summary>
        [Test]
        public void PostStocksTest()
        {
            List<Stock> body = null;
            var response = instance.PostStocks(body);
            Assert.IsInstanceOf<List<Stock>> (response, "response is List<Stock>");
        }
        
    }

}
